Update from node-template
ga-wdi-boston/js-reference-types-practice pull request #84
Opened 2017-01-12 20:29 UTC by BenGitsCode

Refresh for cohort 016

update package.json

2017-01-19 15:19 UTC, jrhorn424 requested changes
Thanks! Please address comments when you get a moment.

Then we'll need to update the solution branch and bonus branch.

2017-01-19 15:19 UTC, jrhorn424 commented on lib/example.js
> +'use strict';
This file is not needed.

2017-01-19 15:19 UTC, jrhorn424 commented on package.json
> +    "start": "node bin/example.js"
This `scripts` property isn't need for now.

2017-01-20 14:05 UTC, BenGitsCode commented
Made those changes Jeff, I made the mistake of pushing before amending my commit, as I'm sure you'll notice.

2017-03-21 02:25 UTC, payne-chris-r commented
Can we close or resolve this?

2017-03-21 02:41 UTC, payne-chris-r commented
@BenGitsCode @jrhorn424 ^

2017-03-21 15:06 UTC, BenGitsCode commented
@payne-chris-r I think this can be closed if Jeff's okay with that. You're working on the lm01 update?

2017-03-21 18:41 UTC, payne-chris-r commented
Thanks @BenGitsCode

2017-03-21 18:41 UTC, closed without merging